'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const adapter=fs.readFileSync(path.join(root,'src','unreal','unrealAdapter.ts'),'utf8');
const tools=fs.readFileSync(path.join(root,'src','unreal','unrealTools.ts'),'utf8');
const merged=fs.readFileSync(path.join(root,'src','tools.ts'),'utf8');
const assets=fs.readFileSync(path.join(root,'src','unreal','unrealAssetTools.ts'),'utf8');
const pipeline=fs.readFileSync(path.join(root,'src','unreal','unrealPipelineTools.ts'),'utf8');
const fracture=fs.readFileSync(path.join(root,'src','unreal','unrealFractureTools.ts'),'utf8');
test('Unreal phase one has explicit adapter routing and safety gates',()=>{assert.match(adapter,/resolveUnrealAdapter/);assert.match(adapter,/execute_(unreal_code|python)/);assert.match(adapter,/evalEnabled/);assert.match(adapter,/no connected Unreal adapter/);assert.match(tools,/unreal.health/);assert.match(tools,/unreal.capabilities/);assert.match(tools,/adapter/);assert.match(merged,/getUnrealTools/);assert.match(merged,/getUnrealAssetTools/);assert.match(assets,/unreal\.asset\.manifest/);assert.match(assets,/unreal\.job\.status/);assert.match(pipeline,/unreal\.pipeline\.validate/);assert.match(pipeline,/unreal\.pipeline\.smoke_test/);assert.match(fracture,/unreal\.fracture\.export_meshes/);assert.match(fracture,/static_physics/);assert.match(fracture,/transform_animation/);assert.match(fracture,/ANIMATION_REQUIRED_FIELDS/);});