import { callUnrealOperation, type UnrealAdapterDependencies } from './unrealAdapter.js';
const adapter={type:'string',minLength:1,description:'Configured Unreal adapter prefix.'};
const confirm={type:'boolean',description:'Required for write operations.'};
const coordinate={type:'object',additionalProperties:false,required:['system','upAxis','handedness','unitScaleMeters'],properties:{system:{type:'string',enum:['ue','unity','godot','blender','custom']},upAxis:{type:'string',enum:['X','Y','Z']},handedness:{type:'string',enum:['left','right']},unitScaleMeters:{type:'number',exclusiveMinimum:0}}};
const range={type:'object',additionalProperties:false,required:['startFrame','endFrame'],properties:{startFrame:{type:'integer',minimum:0},endFrame:{type:'integer',minimum:0},sampleRate:{type:'number',exclusiveMinimum:0}}};
export interface UnrealFractureTool{name:string;description:string;operation:string;inputSchema:Record<string,unknown>;write:boolean;}
const TOOLS:UnrealFractureTool[]=[
{name:'unreal.fracture.export_meshes',description:'Export fractured chunk meshes for external-engine physics or baked transform playback.',operation:'fracture_export_meshes',write:true,inputSchema:{type:'object',additionalProperties:false,required:['source','outputDir','meshFormat','mode'],properties:{adapter,source:{type:'string',minLength:1},outputDir:{type:'string',minLength:1},meshFormat:{type:'string',enum:['glb','gltf','fbx','obj','usd','usda','usdc']},mode:{type:'string',enum:['static_physics','transform_animation','both']},animationFormat:{type:'string',enum:['gltf','fbx','usd','json_tracks']},range,coordinate,mesh:{type:'object'},deterministic:{type:'boolean'},overwrite:{type:'boolean'},dryRun:{type:'boolean'},confirm}}},
{name:'unreal.fracture.export_vat',description:'Export a baked vertex animation texture package from a fractured source.',operation:'fracture_export_vat',write:true,inputSchema:{type:'object',additionalProperties:false,required:['source','outputDir','frameRange','textureFormat'],properties:{adapter,source:{type:'string',minLength:1},outputDir:{type:'string',minLength:1},frameRange:{type:'object',required:['start','end','sampleRate'],properties:{start:{type:'integer',minimum:0},end:{type:'integer',minimum:0},sampleRate:{type:'number',exclusiveMinimum:0}}},textureFormat:{type:'string',enum:['exr','png','hdr']},dryRun:{type:'boolean'},confirm}}},
{name:'unreal.fracture.export_alembic',description:'Export fractured geometry as an Alembic cache.',operation:'fracture_export_alembic',write:true,inputSchema:{type:'object',additionalProperties:false,required:['source','outputFile','frameRange'],properties:{adapter,source:{type:'string',minLength:1},outputFile:{type:'string',minLength:1},frameRange:{type:'object',required:['start','end','fps'],properties:{start:{type:'integer',minimum:0},end:{type:'integer',minimum:0},fps:{type:'number',exclusiveMinimum:0}}},dryRun:{type:'boolean'},confirm}}},
{name:'unreal.fracture.export_skeletal',description:'Export fractured chunks as a skeletal mesh and animation clip.',operation:'fracture_export_skeletal',write:true,inputSchema:{type:'object',additionalProperties:false,required:['source','outputDir','meshFormat','skeletonName','clip'],properties:{adapter,source:{type:'string',minLength:1},outputDir:{type:'string',minLength:1},meshFormat:{type:'string',enum:['fbx','gltf','glb','usd']},skeletonName:{type:'string',minLength:1},clip:{type:'object',required:['name','start','end','fps']},dryRun:{type:'boolean'},confirm}}},
{name:'unreal.fracture.manifest',description:'Read or generate a fracture export manifest and checksums.',operation:'fracture_manifest',write:false,inputSchema:{type:'object',additionalProperties:false,required:['manifestPath'],properties:{adapter,manifestPath:{type:'string',minLength:1},includeChecksums:{type:'boolean'}}}},
{name:'unreal.fracture.validate',description:'Validate fracture manifest files, coordinates, chunks and animation tracks.',operation:'fracture_validate',write:false,inputSchema:{type:'object',additionalProperties:false,required:['manifestPath'],properties:{adapter,manifestPath:{type:'string',minLength:1},strict:{type:'boolean'}}}}
];
export function getUnrealFractureTools(){return TOOLS.map(t=>({...t,inputSchema:{...t.inputSchema,properties:{...((t.inputSchema.properties??{}) as Record<string,unknown>),adapter}}}));}
export function isUnrealFractureTool(name:string){return TOOLS.some(t=>t.name===name);}
function validateFractureArgs(t:UnrealFractureTool,args:Record<string,unknown>){if(t.write&&args.dryRun!==true&&args.confirm!==true)throw new Error('write operation requires confirm=true or dryRun=true');if(t.name==='unreal.fracture.export_meshes'){const mode=args.mode;if(mode==='static_physics'&&args.animationFormat!==undefined)throw new Error('ANIMATION_NOT_ALLOWED_FOR_STATIC_PHYSICS');if((mode==='transform_animation'||mode==='both')&&(args.animationFormat===undefined||args.range===undefined))throw new Error('ANIMATION_REQUIRED_FIELDS');}}
export async function runUnrealFractureTool(name:string,args:Record<string,unknown>,deps?:UnrealAdapterDependencies){const t=TOOLS.find(x=>x.name===name);if(!t)throw new Error('unknown Unreal fracture tool: '+name);validateFractureArgs(t,args);return callUnrealOperation(t.operation,args,deps);}
export async function callCuratedUnrealFractureMcp(name:string,args:Record<string,unknown>,deps?:UnrealAdapterDependencies){try{return{content:[{type:'text' as const,text:await runUnrealFractureTool(name,args,deps)}]};}catch(e){return{content:[{type:'text' as const,text:JSON.stringify({error:e instanceof Error?e.message:String(e)})}],isError:true};}}
export async function callCuratedUnrealFractureRpc(id:unknown,name:string,args:Record<string,unknown>,deps?:UnrealAdapterDependencies){try{return{jsonrpc:'2.0',id,result:{content:[{type:'text' as const,text:await runUnrealFractureTool(name,args,deps)}]}};}catch(e){return{jsonrpc:'2.0',id,error:{code:-32603,message:e instanceof Error?e.message:String(e)}};}}
