import type { BlenderTemplateTool } from './blenderTemplateTools.js';

const q = (v: unknown) => JSON.stringify(String(v));
const n = (v: unknown, d: number) => Number.isFinite(Number(v)) ? Number(v) : d;
const verify = (body: string, summary: string) => body + '\nimport json\nprint(json.dumps(' + summary + ', ensure_ascii=False))\nprint("DONE — verify visually with blender.get_viewport_screenshot")';

const IK: BlenderTemplateTool = { name: 'blender.rig.ik', description: 'Create or update a pose-bone IK constraint.', inputSchema: { type:'object', properties:{rig:{type:'string'},bone:{type:'string'},target:{type:'string'},pole:{type:'string'},chainLength:{type:'integer',minimum:1},name:{type:'string'}}, required:['bone'] }, buildCode(a) { if (!a.bone) throw new Error('bone is required'); const rig=q(a.rig||'bpy.context.active_object'), bone=q(a.bone), target=a.target?q(a.target):'None', pole=a.pole?q(a.pole):'None', chain=Math.max(1,Math.trunc(n(a.chainLength,2))), name=q(a.name||'IK'); return verify('import bpy\nrig=bpy.data.objects.get('+rig+') if isinstance('+rig+',str) else '+rig+'\nif rig is None or rig.type != "ARMATURE": raise RuntimeError("armature rig not found")\nif '+bone+' not in rig.pose.bones: raise RuntimeError("pose bone not found")\ntarget=bpy.data.objects.get('+target+') if '+target+' else None\nif target is None:\n target=bpy.data.objects.new("IK_Target_"+'+bone+',None); bpy.context.collection.objects.link(target)\npole=bpy.data.objects.get('+pole+') if '+pole+' else None\npb=rig.pose.bones['+bone+']\nfor x in list(pb.constraints):\n if x.type=="IK" and x.name=='+name+': pb.constraints.remove(x)\nc=pb.constraints.new("IK"); c.name='+name+'; c.target=target; c.chain_count='+chain+'\nif pole: c.pole_target=pole', '{"rig":rig.name,"bone":pb.name,"target":target.name,"pole":pole.name if pole else None,"chainLength":c.chain_count}'); } };

const NORMALIZE: BlenderTemplateTool = { name:'blender.rig.weights.normalize', description:'Normalize deform vertex-group weights on a skinned mesh.', inputSchema:{type:'object',properties:{mesh:{type:'string'},threshold:{type:'number',minimum:0,maximum:1}}}, buildCode(a) { const mesh=q(a.mesh||'bpy.context.active_object'), threshold=n(a.threshold,0); return verify('import bpy\nmesh=bpy.data.objects.get('+mesh+') if isinstance('+mesh+',str) else '+mesh+'\nif mesh is None or mesh.type!="MESH": raise RuntimeError("mesh not found")\nchanged=0\nfor v in mesh.data.vertices:\n ws=[]\n for g in mesh.vertex_groups:\n  try: ws.append((g,g.weight(v.index)))\n  except RuntimeError: pass\n ws=[(g,w) for g,w in ws if w>='+threshold+']\n total=sum(w for g,w in ws)\n if total>1e-12:\n  for g,w in ws: g.add([v.index],w/total,"REPLACE")\n  changed+=1', '{"mesh":mesh.name,"verticesNormalized":changed,"groups":len(mesh.vertex_groups),"threshold":'+threshold+'}'); } };

const PBR: BlenderTemplateTool = { name:'blender.material.pbr_maps', description:'Build a Principled PBR material and connect texture maps.', inputSchema:{type:'object',properties:{object:{type:'string'},material:{type:'string'},baseColor:{type:'string'},metallic:{type:'string'},roughness:{type:'string'},normal:{type:'string'},height:{type:'string'},emission:{type:'string'}},required:['object']}, buildCode(a) { if(!a.object) throw new Error('object is required'); const obj=q(a.object), mat=q(a.material||'PBR_Maps'), paths=q({baseColor:a.baseColor,metallic:a.metallic,roughness:a.roughness,normal:a.normal,height:a.height,emission:a.emission}); return verify('import bpy\nobj=bpy.data.objects.get('+obj+')\nif obj is None or obj.type!="MESH": raise RuntimeError("mesh object not found")\nmat=bpy.data.materials.get('+mat+') or bpy.data.materials.new('+mat+'); mat.use_nodes=True\nif obj.data.materials: obj.data.materials[0]=mat\nelse: obj.data.materials.append(mat)\nnt=mat.node_tree; bs=nt.nodes.get("Principled BSDF"); paths='+paths+'; connected=[]\ndef tex(label,path,cs="sRGB"):\n if not path: return None\n im=bpy.data.images.load(path,check_existing=True); im.colorspace_settings.name=cs; z=nt.nodes.new("ShaderNodeTexImage"); z.image=im; z.label=label; connected.append(label); return z\ndef link(label,key,cs="sRGB"):\n z=tex(label,paths.get(key),cs)\n if z and key in bs.inputs: nt.links.new(z.outputs["Color"],bs.inputs[key])\nlink("Base Color","baseColor"); link("Metallic","metallic","Non-Color"); link("Roughness","roughness","Non-Color"); link("Emission","emission")\nnormal=tex("Normal",paths.get("normal"),"Non-Color")\nif normal:\n nm=nt.nodes.new("ShaderNodeNormalMap"); nt.links.new(normal.outputs["Color"],nm.inputs["Color"]); nt.links.new(nm.outputs["Normal"],bs.inputs["Normal"])', '{"object":obj.name,"material":mat.name,"maps":connected}'); } };

const BAKE: BlenderTemplateTool = { name:'blender.anim.bake', description:'Bake visual animation and constraints into keyframes.', inputSchema:{type:'object',properties:{rig:{type:'string'},start:{type:'integer'},end:{type:'integer'},step:{type:'integer',minimum:1},clearConstraints:{type:'boolean'}}}, buildCode(a) { const rig=q(a.rig||'bpy.context.active_object'), start=Math.trunc(n(a.start,1)), end=Math.max(start,Math.trunc(n(a.end,250))), step=Math.max(1,Math.trunc(n(a.step,1))), clear=a.clearConstraints===true?'True':'False'; return verify('import bpy\nrig=bpy.data.objects.get('+rig+') if isinstance('+rig+',str) else '+rig+'\nif rig is None: raise RuntimeError("rig not found")\nbpy.ops.object.select_all(action="DESELECT"); rig.select_set(True); bpy.context.view_layer.objects.active=rig\nbpy.ops.nla.bake(frame_start='+start+',frame_end='+end+',step='+step+',only_selected=False,visual_keying=True,clear_constraints='+clear+',use_current_action=True,bake_types={"POSE","OBJECT"})', '{"rig":rig.name,"start":'+start+',"end":'+end+',"step":'+step+'}'); } };

const PREVIEW: BlenderTemplateTool = { name:'blender.anim.preview', description:'Set an animation preview frame and report the active action.', inputSchema:{type:'object',properties:{rig:{type:'string'},frame:{type:'integer'},action:{type:'string'}}}, buildCode(a) { const rig=q(a.rig||'bpy.context.active_object'), frame=Math.trunc(n(a.frame,1)), action=a.action?q(a.action):'None'; return verify('import bpy\nrig=bpy.data.objects.get('+rig+') if isinstance('+rig+',str) else '+rig+'\nif rig is None: raise RuntimeError("rig not found")\nact=bpy.data.actions.get('+action+') if '+action+' else (rig.animation_data.action if rig.animation_data and rig.animation_data.action else None)\nif act: bpy.context.scene.frame_start=int(act.frame_start); bpy.context.scene.frame_end=int(act.frame_end)\nbpy.context.scene.frame_set('+frame+')', '{"rig":rig.name,"frame":bpy.context.scene.frame_current,"action":act.name if act else None}'); } };

const LOOP: BlenderTemplateTool = { name:'blender.anim.loop_check', description:'Check whether action F-curves start and end with matching values.', inputSchema:{type:'object',properties:{action:{type:'string'},tolerance:{type:'number',minimum:0}},required:['action']}, buildCode(a) { if(!a.action) throw new Error('action is required'); const action=q(a.action), tol=n(a.tolerance,.001); return verify('import bpy\nact=bpy.data.actions.get('+action+')\nif act is None: raise RuntimeError("action not found")\nchecks=[abs(fc.keyframe_points[0].co[1]-fc.keyframe_points[-1].co[1])<='+tol+' for fc in act.fcurves if len(fc.keyframe_points)>=2]\nmatched=sum(checks)', '{"action":act.name,"fcurves":len(act.fcurves),"checked":len(checks),"matched":matched,"mismatched":len(checks)-matched,"isLoop":bool(checks) and matched==len(checks),"tolerance":'+tol+'}'); } };

const ADVANCED = [IK,NORMALIZE,PBR,BAKE,PREVIEW,LOOP];
export function getBlenderAdvancedTools(): BlenderTemplateTool[] { return ADVANCED; }
export function isBlenderAdvancedTool(name: string): boolean { return ADVANCED.some(t => t.name === name); }
export async function runBlenderAdvancedTool(name: string, args: Record<string, unknown>, execute: (code: string) => Promise<string>): Promise<string> {
  const tool = ADVANCED.find(t => t.name === name);
  if (!tool) throw new Error(`unknown advanced Blender tool: ${name}`);
  return execute(tool.buildCode(args));
}
